import Image from 'next/image'
import Footer from './components/Footer'
import Nav from './components/Nav'
import './globals.css'
import Logo from "./assets/Logo1.png";
import Logo2 from "./assets/Logo2.png";
import { Montserrat } from 'next/font/google'
// const {Montserrat} = require('next/font/google')

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} text-black bg-white`}>
        <Nav />
        { children }
        <Footer />
      </body>
    </html>
  )
}
